name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run Rufo
        run: bundle exec rufo --check .
      - name: puppet-lint
        uses: scottbrenner/puppet-lint-action@master
        with:
          args: --no-autoloader_layout-check .
